### ISSUE TITLE
Can not install it: undefined symbol: __gxx_personality_v0 - /root/.gem/gems/edlib-0.0.1/lib/edlib/edlib.so (LoadError)

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/ruby-edlib#1]
require "edlib"

Error is:

     /root/.gem/gems/edlib-0.0.1/lib/edlib.rb:1:in `require_relative': /root/.gem/gems/edlib-0.0.1/lib/edlib/edlib.so:
     undefined symbol: __gxx_personality_v0 - /root/.gem/gems/edlib-0.0.1/lib/edlib/edlib.so (LoadError)

I just compiled upstream edlib from source and it installed fine. Source I used for this was:

 https://github.com/Martinsos/edlib/releases

The lib/ I have after compiling the above, has:

    libedlib.a

No idea where the symbol should be **__gxx_personality_v0** though. This error comes when I do
the above require call.

Anyway just reporting this to let you know.

**Comment by kojix2** [comment]
Thank you for your report.
I are not sure what caused this, but I decided to include the edlib source code within the ruby-edlib source code and distribute it together.

Please try the new version to see if it works.
